name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true  # Ensures npm doesn't attempt interactive operations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: MtdrSpring/backend/src/main/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('MtdrSpring/backend/src/main/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"

      - name: Build with Maven
        run: cd MtdrSpring/backend && mvn -B clean compile

      - name: Format Java Code
        run: cd MtdrSpring/backend && mvn com.coveo:fmt-maven-plugin:format

      - name: Lint Java (Checkstyle)
        run: cd MtdrSpring/backend && mvn checkstyle:check

      - name: Run All Tests
        run: cd MtdrSpring/backend && mvn -B test

      - name: NPM Install and Build
        run: |
          cd MtdrSpring/backend/src/main/frontend
          echo "Running npm install..."
          npm install --legacy-peer-deps
          echo "Running npm build..."
          npm run build
        continue-on-error: true  # This will make the step pass even if there are vulnerabilities

      - name: Build Frontend
        run: |
          cd MtdrSpring/backend/src/main/frontend
          npm run build
