name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"

      - name: Build with Maven
        run: cd MtdrSpring/backend && mvn -B clean compile

      - name: Format Java Code (with JDK 17 fix)
        run: |
          cd MtdrSpring/backend
          mvn com.coveo:fmt-maven-plugin:format \
            -DargLine="--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
                       --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED"

      - name: Lint Java (Checkstyle)
        run: cd MtdrSpring/backend && mvn checkstyle:check

      - name: Run All Tests
        run: cd MtdrSpring/backend && mvn -B test

      - name: NPM Security Audit
        run: |
          cd MtdrSpring/backend/src/main/frontend
          npm install
          npm audit --audit-level=critical
